services:
  mysqldb:
    platform: linux/amd64
    image: mysql:8.0.38
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u$MYSQLDB_USER -p$MYSQLDB_PASSWORD" ]
      interval: 30s
      timeout: 30s
      retries: 3
  application:
    depends_on:
      - mysqldb
    restart: on-failure
    image: book-store-service:1.0.0
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
      "spring.datasource.username" : "$MYSQLDB_USER",
      "spring.datasource.password" : "$MYSQLDB_PASSWORD",
      "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
      "spring.jpa.hibernate.ddl-auto" : "validate",
      "spring.jpa.show-sql" : "true",
      "spring.jpa.open-in-view" : "false",
      "server.servlet.context-path" : "/api",
      "spring.jackson.deserialization.fail-on-unknown-properties" : "true",
      "jwt.expiration" : "300000",
      "jwt.secret" : "veryImportantApplicationSecretWithVeryLongName"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
